language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab1-set
  - make -j
  - cd ./bin/
  - ./test_Bruhhhhh 
notifications:
  email: false
